### PR TITLE
Feature/#5 support kube context

### PR DESCRIPTION
**Pull request by sideisra**

### CODE REVIEW

**Review by klg71 — APPROVED** [review]

**Comment by klg71** [comment]
Hey @sideisra thanks for this pull request. I merged it. Could you test the new version 0.0.66 and see if it works for you? :)

**Comment by sideisra** [comment]
I get the message "Incompatible because this component declares an API of a component compatible with Java 17 and the consumer needed a runtime of a component compatible with Java 11". Does the plugin require Java 17?

**Comment by klg71** [comment]
I built it with Java 17 but I can build it with Java 11 too ^^

**Comment by sideisra** [comment]
That would be great :-)

**Comment by klg71** [comment]
Could you try version 0.0.67?

**Comment by sideisra** [comment]
With 0.0.67 i get the same error: Incompatible because this component declares a component compatible with Java 17 and the consumer needed a component compatible with Java 11

**Comment by klg71** [comment]
Ok maybe the version " 0.0.67-11" could work. I will have to release every version for both 11 and 17 now :/

**Comment by sideisra** [comment]
It works with java 11, but Koltin is the problem now. I guess we need to update our setup first.

The binary version of its metadata is 1.8.0, expected version is 1.6.0

**Comment by klg71** [comment]
Ok so I don't have a doing?

**Comment by sideisra** [comment]
No it would be ridiculous to ask you to downgrade kotlin.

**Comment by sideisra** [comment]
But for this feature I could verify that it works by temporarily switching to Java 17 for the gradle build.

**Pull request merged**
